stages:
  - build
  - test

variables:
  IMAGE_COMMIT: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  IMAGE_BRANCH: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  IMAGE_LATEST: $CI_REGISTRY/$CI_PROJECT_PATH:latest

image: docker:17.06

static-analysis:
  stage: build
  image: coala/base:0.11
  script:
    - coala --non-interactive

build:
  stage: build
  script:
    - docker build -t $IMAGE_COMMIT .

test:
  stage: test
  image: $IMAGE_COMMIT
  script:
    - python manage.py test

pylint:
  stage: test
  image: $IMAGE_COMMIT
  script:
    - pip install pylint && pylint apps {{ cookiecutter.package_name }}

push:
  stage: deploy
  script:
    - docker tag $IMAGE_COMMIT $IMAGE_LATEST
    - docker push $IMAGE_LATEST
  when: manual
