---
repos:
  - repo: local
    hooks:
      - id: black
        name: black-code-formatter
        language: docker_image
        entry: --entrypoint black kiwicom/black:23.11.0
        args: ["--line-length", "120", "apps/", "{{ cookiecutter.package_name }}", "bin/"]
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
        exclude: ^(tests/unit/data/|scripts/|config/)
      - id: trailing-whitespace
        exclude: ^(tests/unit/data/|scripts/|config/)

  - repo: https://github.com/PyCQA/isort
    rev: 6.1.0
    hooks:
      - id: isort
        additional_dependencies: ["toml"]

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.9
    hooks:
      - id: pylint
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display score
            "--disable=import-error", # Ignore import errors in isolated environment
          ]
